spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "*"
            allowed-methods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
            allow-credentials: true
            allowed-headers:
              - "8"
      routes:
        - id: todos
          uri: http://localhost
          predicates:
            - Path=/api/v1/todos/**
          filters:
            - AddResponseHeader=Access-Control-Allow-Origin, http://localhost:5173
            - AddResponseHeader=Access-Control-Allow-Methods, "GET, POST, PUT, DELETE, OPTIONS"
            - AddResponseHeader=Access-Control-Allow-Headers, "*"
            - AddResponseHeader=Access-Control-Allow-Credentials, "true"
  main:
    web-application-type: reactive
#      mvc:
#        routes:
#          - id: todos
#            uri: http://localhost:8089
#            predicates:
#              - Path=/api/v1/todos